<a href="https://colab.research.google.com/github/BENWWWW/AI-DEEPLEARNING/blob/main/03_ML_DNN_DL_JeffersonRubenSulaiman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras.layers import Dense, Input
from keras.models import Sequential
from keras.callbacks import History
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [50]:
data = pd.read_csv('/content/sample_data/glass.csv')
X = data[['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe']].values
y = data['Type'].values  # labels

print("Data loaded successfully.")
display(data.head())
np.shape(X)


Data loaded successfully.


RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

(214, 9)

In [11]:
np.shape(y)

(214,)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2021) #Splitting dataset

In [62]:
#define the model
model = Sequential([
    Input(shape=(9,)),
    Dense(60, activation='relu'), #HL
    Dense(60, activation='relu'),
    Dense(8, activation='softmax') #Output
])

In [32]:
#compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

#train the model
model.fit(X_train, y_train, epochs=30, batch_size=32, verbose=1)

Epoch 1/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.2933 - loss: 5.1357
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2509 - loss: 2.9206 
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3833 - loss: 2.1522 
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4271 - loss: 2.1364 
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3626 - loss: 1.8077 
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3132 - loss: 1.7254 
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3804 - loss: 1.4325 
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4655 - loss: 1.3995 
Epoch 9/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3992 - loss: 1.4743  
Epoch 10/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3005 - loss: 1.4130 
Epoch 11/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4660 - loss: 1.3964 
Epoch 12/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4559 - loss: 1.3785 
E

In [35]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5775 - loss: 1.2264
Test Loss: 1.2518815994262695
Test Accuracy: 0.5846154093742371


In [37]:
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import classification_report, confusion_matrix

model_linear = LinearSVC(C=0.1 ,random_state=2021, max_iter=5000, loss='squared_hinge')
model_linear2 = SVC(C=1 ,kernel='linear', probability=True)
model_non_linear = SVC(C=1 ,kernel='poly', probability=True)

model_linear.fit(X_train, y_train)
model_linear2.fit(X_train, y_train)
model_non_linear.fit(X_train, y_train)

SVC(C=1, kernel='poly', probability=True)

In [38]:
# make predictions from the model_linear and model_non_linear
Y_pred_linear = model_linear.predict(X_test)
Y_pred_nonlinear = model_non_linear.predict(X_test)

#confusion matrix
conf_matrix_linear = confusion_matrix(y_test, Y_pred_linear)
print("Confusion Matrix for Linear Model: \n", conf_matrix_linear)
print()

conf_matrix_nonlinear = confusion_matrix(y_test, Y_pred_nonlinear)
print("Confusion Matrix for non-Linear Model: \n", conf_matrix_nonlinear)
print()

#accuracy
accuracy_linear = model_linear.score(X_test, y_test)
print("Accuracy for Linear Model: %.2f \n" % accuracy_linear)

accuracy_nonlinear = model_non_linear.score(X_test, y_test)
print("Accuracy for non-Linear Model: %.2f \n" % accuracy_nonlinear)

#classification report
print("Classification Report For Linear Model: \n", classification_report(y_test, Y_pred_linear))
print("Classification Report For non-Linear Model: \n", classification_report(y_test, Y_pred_nonlinear))

#manual accuracy
# manual_acc = sum(conf_matrix[i][i] for i in range(len(conf_matrix))) / len(Y_pred)
# print("Manually Calculated Accuracy: %.2f " % manual_acc)

Confusion Matrix for Linear Model: 
 [[ 9 15  0  0  0  0]
 [ 2 13  0  1  0  1]
 [ 4  2  0  0  0  0]
 [ 0  1  0  2  0  1]
 [ 0  1  0  0  0  3]
 [ 0  1  0  0  0  9]]

Confusion Matrix for non-Linear Model: 
 [[ 0 24  0  0  0  0]
 [ 0 17  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0 10  0  0  0  0]]

Accuracy for Linear Model: 0.51 

Accuracy for non-Linear Model: 0.26 

Classification Report For Linear Model: 
               precision    recall  f1-score   support

           1       0.60      0.38      0.46        24
           2       0.39      0.76      0.52        17
           3       0.00      0.00      0.00         6
           5       0.67      0.50      0.57         4
           6       0.00      0.00      0.00         4
           7       0.64      0.90      0.75        10

    accuracy                           0.51        65
   macro avg       0.38      0.42      0.38        65
weighted avg       0.46      0.51      0.46        65

Classific

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/m

In [40]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize and train the Naïve Bayes classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = nb_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.4
Confusion Matrix:
 [[ 6  1 17  0  0  0]
 [ 1  3  9  4  0  0]
 [ 1  1  3  0  1  0]
 [ 0  1  0  2  0  1]
 [ 0  0  0  0  3  1]
 [ 0  0  1  0  0  9]]
Classification Report:
               precision    recall  f1-score   support

           1       0.75      0.25      0.38        24
           2       0.50      0.18      0.26        17
           3       0.10      0.50      0.17         6
           5       0.33      0.50      0.40         4
           6       0.75      0.75      0.75         4
           7       0.82      0.90      0.86        10

    accuracy                           0.40        65
   macro avg       0.54      0.51      0.47        65
weighted avg       0.61      0.40      0.42        65



In [41]:
#random forest technique
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest Classifier
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [44]:
#Use the trained model to make predictions on the test set:
# Make predictions on the test set

y_pred = rf_clf.predict(X_test)

#Evaluate the model's performance by calculating the accuracy:
# Calculate accuracy

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.74


In [46]:
#K nearest neighbour
from sklearn.neighbors import KNeighborsClassifier

# Initialize the kNN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 66.15%


In [66]:
#DEEP NEURAL NETWORK
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [76]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_dnn = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(16, activation='relu'),
    BatchNormalization(),

    Dense(8, activation='softmax')
])

model_dnn.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10)

history = model_dnn.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=16,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

loss, acc = model_dnn.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Deep Neural Network Test Accuracy: {acc:.4f}")

Epoch 1/200


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 5s 62ms/step - accuracy: 0.1277 - loss: 2.4659 - val_accuracy: 0.4333 - val_loss: 2.0360 - learning_rate: 0.0010
Epoch 2/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2446 - loss: 2.1510 - val_accuracy: 0.5333 - val_loss: 1.9841 - learning_rate: 0.0010
Epoch 3/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2420 - loss: 2.1393 - val_accuracy: 0.5667 - val_loss: 1.9271 - learning_rate: 0.0010
Epoch 4/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3208 - loss: 1.9287 - val_accuracy: 0.5667 - val_loss: 1.8719 - learning_rate: 0.0010
Epoch 5/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3267 - loss: 1.8339 - val_accuracy: 0.6000 - val_loss: 1.8134 - learning_rate: 0.0010
Epoch 6/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4566 - loss: 1.6209 - val_accuracy: 0.6000 - val_loss: 1.7624 - learning_rate: 0.0010
Epoch 7/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4577 - loss: 1.5761 - val_accuracy: 0.6000 - val

In [77]:
# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [81]:
from keras.utils import to_categorical

# One-hot encode labels
y_train_onehot = to_categorical(y_train, num_classes=8)
y_test_onehot = to_categorical(y_test, num_classes=8)

# Build Deep Neural Network
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(16, activation='relu'),
    BatchNormalization(),

    Dense(8, activation='softmax')   # output sesuai jumlah kelas
])

# Compile model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',  # cocok untuk one-hot label
    metrics=['accuracy']
)

# Train model
history = model.fit(
    X_train, y_train_onehot,
    validation_split=0.2,
    epochs=200,
    batch_size=16,
    verbose=1
)

# Evaluate
loss, acc = model.evaluate(X_test, y_test_onehot, verbose=0)
print(f"Test Accuracy: {acc:.4f}")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - accuracy: 0.1132 - loss: 2.6626 - val_accuracy: 0.2667 - val_loss: 2.0602
Epoch 2/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1298 - loss: 2.3954 - val_accuracy: 0.1333 - val_loss: 2.0592
Epoch 3/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2567 - loss: 2.0911 - val_accuracy: 0.0667 - val_loss: 2.0469
Epoch 4/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1839 - loss: 2.1975 - val_accuracy: 0.2000 - val_loss: 2.0310
Epoch 5/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2286 - loss: 2.1222 - val_accuracy: 0.3000 - val_loss: 2.0111
Epoch 6/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3549 - loss: 1.8954 - val_accuracy: 0.3667 - val_loss: 1.9995
Epoch 7/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4292 - loss: 1.6939 - val_accuracy: 0.3333 - val_loss: 1.9877
Epoch 8/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4222 - loss: 1.6698 - val_accuracy: 0.3000 - val_loss:

In [82]:
pip install ucimlrepo

In [83]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer = fetch_ucirepo(id=14)

# data (as pandas dataframes)
X = breast_cancer.data.features
y = breast_cancer.data.targets

print(X)
print(y)

       age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
0    30-39   premeno      30-34       0-2        no          3   left   
1    40-49   premeno      20-24       0-2        no          2  right   
2    40-49   premeno      20-24       0-2        no          2   left   
3    60-69      ge40      15-19       0-2        no          2  right   
4    40-49   premeno        0-4       0-2        no          2  right   
..     ...       ...        ...       ...       ...        ...    ...   
281  30-39   premeno      30-34       0-2        no          2   left   
282  30-39   premeno      20-24       0-2        no          3   left   
283  60-69      ge40      20-24       0-2        no          1  right   
284  40-49      ge40      30-34     5-Mar        no          3   left   
285  50-59      ge40      30-34     5-Mar        no          3   left   

    breast-quad irradiat  
0      left_low       no  
1      right_up       no  
2      left_low       no  
3       left_up